### ISSUE TITLE
request.headers.append does not exist

### ISSUE THREAD

**Issue by vangundy** [freshcutdevelopment/Aurelia-in-Action#12]
Running aurelia-http-client 1.2.1, I had to change part of **Listing 10.4** to this:
```javascript
get tokenInterceptor() {
    let self = this;
    return {
      request(request: RequestMessage): RequestMessage | Promise<RequestMessage> {
        let token = self.token;
        if (token) {
          request.headers.add('authorization', `bearer ${token}`)
        }
        return request;
      }
    };
  }
```

**Comment by freshcutdevelopment** [comment]
Thanks @vangundy! Really appreciate the feedback. Will review and get the code samples updated.

**Comment by freshcutdevelopment** [comment]
Hi @vangundy, I've tested the existing version using ` "aurelia-fetch-client": "^1.3.1"` (ESNext) and found that it's working without modification. Perhaps this is something that's since been fixed.

Do you still receive an error in 1.3.1? If so, could you let me know a bit more about the nature of the error?
