### ISSUE TITLE
Section: "1.4.2 Handling DOM Events", might have a wrong illustration.

### ISSUE THREAD

**Issue by vpanjganj** [freshcutdevelopment/Aurelia-in-Action#2]

**Comment by freshcutdevelopment** [comment]
Thanks for raising this issue here @vpanjganj, really appreciate your input. This has now been corrected in the latest MEAP update. On checking it has not quite made it into the live book's version yet, so I'll leave this issue open to track when it is updated there as well. If you download the latest MEAP you should get the corrected image :relieved:

**Comment by freshcutdevelopment** [comment]
This image has now been updated on liveBook as well so I'll close this off. 

Thanks again
